config/routes.rb
Depends::Application.routes.draw do

   root :to => 'nodes#index'

  resources :nodes
  resources :relationship_groups

end

app/models/node.rb
class Node < ActiveRecord::Base

  has_many :node_relationship_groups
  has_many :relationship_groups, :through => :node_relationship_groups

  scope :available, where(:available => true)

  attr_accessible :name

  validates :name, :presence => true, :uniqueness => true

  def satisfied?
    relationship_groups.all? &:satisfied?
  end

  def to_s
    name
  end

end

app/models/node_relationship_group.rb
class NodeRelationshipGroup < ActiveRecord::Base
  belongs_to :relationship_group
  belongs_to :node
end

app/models/relationship_group.rb
class RelationshipGroup < ActiveRecord::Base
  has_many :relationship_nodes
  has_many :node_relationship_groups
  has_many :rnodes, :through => :relationship_nodes, :class_name => 'Node', :source => :node
  has_many :nodes, :through => :node_relationship_groups, :class_name => 'Node', :source => :node

  attr_accessible :rnode_ids
  attr_accessible :minimum
  attr_accessible :name
  
  def satisfied?
    rnodes.available.count >= ( minimum > -1 ) ? minimum : rnodes.count
  end
  
  def satisfied_by
    ( minimum > -1 ) ? "at least #{minimum}" : 'all'
  end
  
  def to_s
    name
  end

end

app/models/relationship_node.rb
class RelationshipNode < ActiveRecord::Base
  belongs_to :relationship_group
  belongs_to :node
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController

  expose(:nodes) {Node.all}
  expose(:node)

  def new
  end

  def create
    if node.save
      flash[:notice] = "Node successfully created"
      redirect_to nodes_path
    else
      render :action => 'new'
    end
  end

  def index
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => nodes }
      format.json { render :json => nodes }
    end
  end

  def show
  end

  def edit
  end

  def update
    if node.update_attributes(params[:node])
      flash[:notice] = 'Node updated'
      redirect_to nodes_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    node.destroy
    flash[:notice] = "Node deleted"
    redirect_to nodes_path
  end

end

app/controllers/relationship_groups_controller.rb
class RelationshipGroupsController < ApplicationController

  expose(:relationship_groups) {RelationshipGroup.all}
  expose(:relationship_group)
  
  def new
  end

  def create
    if relationship_group.save
      flash[:notice] = "Relationship Group successfully created"
      redirect_to relationship_groups_path
    else
      render :action => 'new'
    end
  end

  def index
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => relationship_groups }
      format.json { render :json => relationsip_groups }
    end
  end

  def show
  end

  def edit
  end

  def update
    if relationship_group.update_attributes(params[:relationship_group])
      flash[:notice] = 'Relationship Group updated'
      redirect_to relationship_groups_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    relationship_group.destroy
    flash[:notice] = "Relationship Group deleted"
    redirect_to relationship_groups_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper

  def link_to_self(object, options = {})
    link_to(object, object, options)
  end

end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to "Home", root_path, :class => 'brand'
%ul.nav
  %li Nodes

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Myapp"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer

app/views/nodes/_form.html.haml
=semantic_form_for(node) do |form|
  =form.inputs do
    =form.input :name
  =form.buttons do
    =form.commit_button 'Save'

app/views/nodes/_show.html.haml
%h1=node

.depends
   =render :partial => 'relationship_groups/show', :collection => node.relationship_groups, :as => 'relationship_group'

app/views/nodes/edit.html.haml
%h1 Edit node
=render 'form', :node => node

app/views/nodes/index.html.haml
%h1 Nodes are coming

%ul
  -nodes.each do |node|
    %li=link_to_self node
=link_to 'New node', new_node_path, :class => 'btn'

app/views/nodes/new.html.haml
%h1 New node
=render 'form', :node => node

app/views/nodes/show.html.haml
=render 'show', :node => node
=link_to 'Edit', edit_node_path(node), :class => 'btn'
=link_to 'Delete', node, :confirm => 'Are you sure?', :method => :delete, :class => 'btn'

app/views/relationship_groups/_form.html.haml
=semantic_form_for(relationship_group) do |form|
  =form.inputs do
    =form.input :name
    =form.input :minimum
    =form.input :rnodes
  =form.buttons do
    =form.commit_button 'Save'

app/views/relationship_groups/_show.html.haml
%h2 Requires #{relationship_group.satisfied_by}
-relationship_group.rnodes.each do |rnode|
  %li=link_to_self rnode

app/views/relationship_groups/edit.html.haml
%h1 Edit relationship group
=render 'form', :relationship_group => relationship_group

app/views/relationship_groups/index.html.haml
%h1 Relationship Groups

%ul
  -relationship_groups.each do |relationship_group|
    %li=link_to_self relationship_group
=link_to 'New relationship group', new_relationship_group_path, :class => 'btn'

app/views/relationship_groups/new.html.haml
%h1 New relationship group
=render 'form', :relationship_group => relationship_group

app/views/relationship_groups/show.html.haml
%h1=relationship_group.name
=render 'show', :relationship_group => relationship_group
=link_to 'Edit', edit_relationship_group_path(relationship_group), :class => 'btn'
=link_to 'Delete', relationship_group, :confirm => 'Are you sure?', :method => :delete, :class => 'btn'